### ISSUE TITLE
Undefined method `patch' when brew upgrading bayeux

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/homebrew-cadfael#43]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not brew? If it's a general brew problem please file this issue at https://github.com/supernemo-dbd/brew/issues/new

My Mac had helpfully auto-updated to Xcode 9, meaning I couldn't build SensitivityModule any more, so I decided to `brew upgrade` to the latest High Sierra-friendly version of everything. I saw this error quite early in the upgrade process and tried installing packages one at a time. So now I have ROOT, GEANT etc but Bayeux will not upgrade. 

Error is: 

```
Cheryls-MacBook-Pro:CadfaelBrew cpatrick$ brew upgrade bayeux
==> Upgrading 1 outdated package, with result:
supernemo-dbd/cadfael/bayeux 3.0.0_5
Error: undefined method `patch' for #<Resource:0x00000101524a70>
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/Users/cpatrick/CadfaelBrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:66:in `block (2 levels) in <class:Llvm>'
/Users/cpatrick/CadfaelBrew/Library/Homebrew/resource.rb:49:in `instance_eval'
```
(... there is a long list of "in" lines which I can give you if you want)

Here is the [gist log](https://gist.github.com/cherylepatrick/2197b13bd661f328d3d7376f5a38cec0)

**Comment by cherylepatrick** [comment]
Just in case it's relevant - I've been using a non-standard falaise. Don't know if I still need to be.
```
Cheryls-MacBook-Pro:CadfaelBrew cpatrick$ brew upgrade
==> Upgrading 3 outdated packages, with result:
supernemo-dbd/cadfael/bayeux 3.0.0_5, supernemo-dbd/cadfael/falaise HEAD-682c1cf_1, supernemo-dbd/cadfael/ptd2root 1.0.0_1
Error: undefined method `patch' for #<Resource:0x00000101080078>
```
